name: Debug Ansible

on:
  workflow_dispatch:

jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 --decode > ./id_rsa
          chmod 600 ./id_rsa

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
      
      - name: Ansible ping hosts 
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          cd config
          ansible -i inventory.ini nodes -m ping