name: Terraform CI/CD

on:
    push:
        branches:
            - main

jobs:
    terraform:
        name: Deploy terraform infra to AWS
        
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up AWS creds
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.1.7"

            - name: Select environment
              run: |
                if [[ $GITHUB_REF_NAME == "dev" ]]; then
                    BACKEND_FILE=backend-dev.hcl
                elif [[ $GITHUB_REF_NAME = "staging" ]]; then
                    BACKEND_FILE=backend-staging.hcl
                else
                    BACKEND_FILE=backend-prod.hcl
                fi
                echo "Using backend $BACKEND_FILE"
                echo "BACKEND_FILE=$BACKEND_FILE" >> $GITHUB_ENV

            - name: Terraform init
              run: terraform -chdir=infra init -backend-config=$BACKEND_FILE

            - name: Terraform plan
              run: terraform -chdir=infra plan

            - name: Terraform apply
              run: terraform -chdir=infra apply -auto-approve

    build-frontend:
        name: Build Vue front and upload artifact
        
        needs: terraform
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Install dependencies
              run: |
                cd app
                npm ci

            - name: Build
              run: |
                cd app
                npm run build

            - name: Upload built artifact
              uses: actions/upload-artifact@v4
              with:
                name: frontend-build
                path: app/dist